
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Warden_MVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class commands
{

    public int idc { get; set; }

    public string ctype { get; set; }

    public int destination_idb { get; set; }

}

}
