//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warden_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_beacons
    {
        public int idnb { get; set; }
    
        public virtual all_beacons all_beacons { get; set; }
    }
}
